"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import { Amplify } from "aws-amplify";
import awsExports from "../aws-exports";
import { withAuthenticator } from "@aws-amplify/ui-react";

// Amplify 設定を適用
Amplify.configure(awsExports);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Catawiki Products",
  description: "Generated by AWS Amplify and Next.js",
};

// 認証付きのレイアウトを作成
function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// 認証が必要なレイアウトとしてエクスポート
export default withAuthenticator(RootLayout);
